server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        #自定义事务组名称需要与seata-server中的对应
        tx-service-group: fsp_tx_group
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://49.235.60.52:3307/seata_order
    username: root
    password: 123456

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false  #关闭 /开启hystrix超时


ribbon:
  #建立连接所用时间5s
  ReadTimeout:  10000
  #建立连接后从服务端读取到可用资源的时间5s
  ConnectTimeout: 10000

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml